import os
import re

def extract_metadata(content):
    """Extracts title and description from Next.js metadata object."""
    metadata = {"title": "", "description": ""}
    
    title_match = re.search(r'title:\s*["\'](.*?)["\']', content)
    if title_match:
        metadata["title"] = title_match.group(1)
        
    desc_match = re.search(r'description:\s*["\'](.*?)["\']', content)
    if desc_match:
        metadata["description"] = desc_match.group(1)
        
    return metadata

def clean_text(text):
    """Cleans HTML tags and JS expressions from text."""
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'\{.*?\}', '', text) # Remove JS expressions
    text = text.replace('\n', ' ').strip()
    return ' '.join(text.split())

def extract_hierarchical_content(content):
    """Extracts content nodes while preserving their document order."""
    # Find all headings, paragraphs, and list items in order
    pattern = re.compile(r'<(h[1-6]|p|li)[^>]*>(.*?)</\1>', re.DOTALL)
    matches = pattern.findall(content)
    
    nodes = []
    for tag, body in matches:
        cleaned = clean_text(body)
        if cleaned:
            nodes.append({"tag": tag, "content": cleaned})
    
    return nodes

def generate_markdown(route, metadata, nodes):
    """Constructs a structured Markdown file from hierarchical nodes."""
    md = []
    if metadata["title"]:
        md.append(f"--- title: {metadata['title']} ---")
    
    md.append(f"# {metadata['title'] or route.capitalize()}")
    
    if metadata["description"]:
        md.append(f"\n> {metadata['description']}\n")
    
    md.append("\n## Semantic Content Architecture\n")
    
    for node in nodes:
        tag = node["tag"]
        content = node["content"]
        
        if tag.startswith('h'):
            level = int(tag[1])
            # Normalize levels (h1 -> h2, h2 -> h3 etc. to fit under the main title)
            md.append(f"\n{'#' * (level + 1)} {content}")
        elif tag == 'p':
            md.append(f"\n{content}")
        elif tag == 'li':
            md.append(f"- {content}")
            
    md.append(f"\n\n--- \nSource: https://quroixlabs.com{route}")
    md.append("\nGenerated by Quroix Labs Hierarchical Mirror System (v2.0 - AEO/GEO Optimized)")
    
    return "\n".join(md)

def update_llms_txt(mirrors_map):
    """Updates the llms.txt file with links to all generated mirrors."""
    llms_path = "public/llms.txt"
    if not os.path.exists(llms_path):
        return
        
    with open(llms_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    mirror_section_header = "## Full Sitemap (Markdown Mirrors)"
    
    # Generate the new section content
    links = []
    base_url = "https://quroixlabs.com/mirrors"
    
    # Sort for consistency
    for route in sorted(mirrors_map.keys()):
        m_name = mirrors_map[route]
        # Human readable name
        h_name = route.replace("/", " ").strip().title() or "Home"
        links.append(f"- **{h_name}**: {base_url}/{m_name}.md")
        
    new_section = f"{mirror_section_header}\n" + "\n".join(links)
    
    # Replace or append
    if mirror_section_header in content:
        pattern = re.compile(rf"{re.escape(mirror_section_header)}.*?(?=\n##|$)", re.DOTALL)
        new_content = pattern.sub(new_section + "\n\n", content)
    else:
        if "## Technical Contact" in content:
            new_content = content.replace("## Technical Contact", f"{new_section}\n\n## Technical Contact")
        else:
            new_content = content + f"\n\n{new_section}"
            
    with open(llms_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Updated {llms_path} with {len(links)} mirror links.")

def run():
    app_dir = "app"
    target_dir = "public/mirrors"
    
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
        
    routes_found = {}
    
    for root, dirs, files in os.walk(app_dir):
        if "page.jsx" in files or "page.tsx" in files:
            page_file = "page.jsx" if "page.jsx" in files else "page.tsx"
            page_path = os.path.join(root, page_file)
            
            rel_path = os.path.relpath(root, app_dir)
            route = "/" if rel_path == "." else f"/{rel_path.replace(os.sep, '/')}"
            mirror_name = "index" if route == "/" else rel_path.replace(os.sep, '_')
            
            with open(page_path, "r", encoding="utf-8") as f:
                page_content = f.read()
            
            metadata = extract_metadata(page_content)
            
            # For hierarchical mirroring, we need to collect all nodes from all components in this route
            all_nodes = []
            
            # First, check components in the same folder as page.jsx
            for file in files:
                if (file.endswith(".jsx") or file.endswith(".tsx")) and file != "layout.jsx":
                    with open(os.path.join(root, file), "r", encoding="utf-8") as f:
                        all_nodes.extend(extract_hierarchical_content(f.read()))
            
            # Special case for Home page (Main folder)
            if route == "/":
                main_dir = os.path.join(app_dir, "Main")
                if os.path.exists(main_dir):
                    # We want to process these in a specific order if possible, but for now we walk
                    for m_root, m_dirs, m_files in os.walk(main_dir):
                        for m_file in m_files:
                            if m_file.endswith(".jsx") or m_file.endswith(".tsx"):
                                with open(os.path.join(m_root, m_file), "r", encoding="utf-8") as f:
                                    all_nodes.extend(extract_hierarchical_content(f.read()))

            # De-duplicate adjacent identical nodes (artifact of multi-component extraction)
            deduped_nodes = []
            for node in all_nodes:
                if not deduped_nodes or node != deduped_nodes[-1]:
                    deduped_nodes.append(node)

            md_content = generate_markdown(route, metadata, deduped_nodes)
            
            target_path = os.path.join(target_dir, f"{mirror_name}.md")
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(md_content)
                
            routes_found[route] = mirror_name
            print(f"Generated hierarchical mirror for {route} -> {target_path}")

    update_llms_txt(routes_found)
    print(f"\nDone. Successfully generated {len(routes_found)} dynamic mirrors.")

if __name__ == "__main__":
    run()
