import os
import re

def extract_metadata(content):
    """Extracts title and description from Next.js metadata object."""
    metadata = {"title": "", "description": ""}
    
    title_match = re.search(r'title:\s*["\'](.*?)["\']', content)
    if title_match:
        metadata["title"] = title_match.group(1)
        
    desc_match = re.search(r'description:\s*["\'](.*?)["\']', content)
    if desc_match:
        metadata["description"] = desc_match.group(1)
        
    return metadata

def extract_text_from_jsx(content):
    """Extracts text from common HTML tags in JSX."""
    # Remove HTML tags but keep content
    # This is a simple regex-based extractor for JSX/HTML content
    
    # Extract headings
    headings = re.findall(r'<h[1-6][^>]*>(.*?)</h[1-6]>', content, re.DOTALL)
    # Extract paragraphs
    paragraphs = re.findall(r'<p[^>]*>(.*?)</p>', content, re.DOTALL)
    # Extract list items
    list_items = re.findall(r'<li[^>]*>(.*?)</li>', content, re.DOTALL)
    
    # Clean up tags inside the extracted text (e.g. <br />, <span>)
    def clean(text):
        text = re.sub(r'<[^>]+>', ' ', text)
        text = re.sub(r'\{.*?\}', '', text) # Remove JS expressions
        text = text.replace('\n', ' ').strip()
        return ' '.join(text.split())

    return {
        "headings": [clean(h) for h in headings if clean(h)],
        "paragraphs": [clean(p) for p in paragraphs if clean(p)],
        "list_items": [clean(l) for l in list_items if clean(l)]
    }

def generate_markdown(route, metadata, content_blocks):
    """Constructs a clean Markdown file from extracted data."""
    md = []
    if metadata["title"]:
        md.append(f"--- title: {metadata['title']} ---")
    
    md.append(f"# {metadata['title'] or route.capitalize()}")
    
    if metadata["description"]:
        md.append(f"\n> {metadata['description']}\n")
        
    if content_blocks["headings"]:
        md.append("## Key Highlights")
        for h in content_blocks["headings"]:
            if h.lower() not in [metadata["title"].lower(), route.lower()]:
                md.append(f"### {h}")
                
    if content_blocks["paragraphs"]:
        md.append("\n## Detailed Overview")
        for p in content_blocks["paragraphs"]:
            md.append(f"\n{p}")
            
    if content_blocks["list_items"]:
        md.append("\n## Key Details")
        for l in content_blocks["list_items"]:
            md.append(f"- {l}")
            
    md.append(f"\n\n--- \nSource: https://quroixlabs.com{route}")
    md.append("\nGenerated by QuroixLabs Dynamic Markdown Mirror System")
    
    return "\n".join(md)

def update_llms_txt(mirrors_map):
    """Updates the llms.txt file with links to all generated mirrors."""
    llms_path = "public/llms.txt"
    if not os.path.exists(llms_path):
        return
        
    with open(llms_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    mirror_section_header = "## Markdown Mirrors (Plain Text for AI Indexing)"
    
    # Generate the new section content
    links = []
    base_url = "https://quroixlabs.com/mirrors"
    
    # Sort for consistency
    for route in sorted(mirrors_map.keys()):
        m_name = mirrors_map[route]
        # Human readable name
        h_name = route.replace("/", " ").strip().title() or "Home"
        links.append(f"- **{h_name}**: {base_url}/{m_name}.md")
        
    new_section = f"{mirror_section_header}\n" + "\n".join(links)
    
    # Replace or append
    if mirror_section_header in content:
        # Replace existing section
        pattern = re.compile(rf"{re.escape(mirror_section_header)}.*?(?=\n##|$)", re.DOTALL)
        new_content = pattern.sub(new_section + "\n\n", content)
    else:
        # Append before technical contact or at end
        if "## Technical Contact" in content:
            new_content = content.replace("## Technical Contact", f"{new_section}\n\n## Technical Contact")
        else:
            new_content = content + f"\n\n{new_section}"
            
    with open(llms_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Updated {llms_path} with {len(links)} mirror links.")

def run():
    app_dir = "app"
    target_dir = "public/mirrors"
    
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
        
    routes_found = {}
    
    for root, dirs, files in os.walk(app_dir):
        if "page.jsx" in files or "page.tsx" in files:
            page_file = "page.jsx" if "page.jsx" in files else "page.tsx"
            page_path = os.path.join(root, page_file)
            
            rel_path = os.path.relpath(root, app_dir)
            route = "/" if rel_path == "." else f"/{rel_path.replace(os.sep, '/')}"
            mirror_name = "index" if route == "/" else rel_path.replace(os.sep, '_')
            
            with open(page_path, "r", encoding="utf-8") as f:
                page_content = f.read()
            
            metadata = extract_metadata(page_content)
            
            full_text_blocks = {"headings": [], "paragraphs": [], "list_items": []}
            
            for file in files:
                if (file.endswith(".jsx") or file.endswith(".tsx")) and file != "layout.jsx":
                    with open(os.path.join(root, file), "r", encoding="utf-8") as f:
                        file_content = f.read()
                        blocks = extract_text_from_jsx(file_content)
                        for key in full_text_blocks:
                            full_text_blocks[key] = list(dict.fromkeys(full_text_blocks[key] + blocks[key]))
            
            if route == "/":
                main_dir = os.path.join(app_dir, "Main")
                if os.path.exists(main_dir):
                    for m_root, m_dirs, m_files in os.walk(main_dir):
                        for m_file in m_files:
                            if m_file.endswith(".jsx") or m_file.endswith(".tsx"):
                                with open(os.path.join(m_root, m_file), "r", encoding="utf-8") as f:
                                    m_content = f.read()
                                    blocks = extract_text_from_jsx(m_content)
                                    for key in full_text_blocks:
                                        full_text_blocks[key] = list(dict.fromkeys(full_text_blocks[key] + blocks[key]))

            md_content = generate_markdown(route, metadata, full_text_blocks)
            
            target_path = os.path.join(target_dir, f"{mirror_name}.md")
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(md_content)
                
            routes_found[route] = mirror_name
            print(f"Generated mirror for {route} -> {target_path}")

    update_llms_txt(routes_found)
    print(f"\nDone. Successfully generated {len(routes_found)} dynamic mirrors.")


if __name__ == "__main__":
    run()
